/**
 * Generates the globe artwork for the EZ 2 SHIP badge logo from Natural Earth data:
 * an orthographic view centred near the Florida headquarters, with graticule lines.
 * Output: src/components/brand/globePaths.ts
 *
 *   node scripts/build-logo.mjs
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import { createRequire } from 'node:module';
import { feature } from 'topojson-client';
import { geoOrthographic, geoPath, geoGraticule } from 'd3-geo';

const require = createRequire(import.meta.url);
const topo = require('world-atlas/land-110m.json');
const land = feature(topo, topo.objects.land);

// Badge coordinate system (viewBox 0 0 240 240): globe centred at (120, 94), radius 78.
const projection = geoOrthographic()
  .rotate([78, -24, 0])
  .scale(78)
  .translate([120, 94])
  .clipAngle(90)
  .precision(0.7);

/** Round to 0.1 units and drop vertices closer than `min` to the previous one — plenty for a logo. */
function round(d, min = 0.7) {
  const out = [];
  for (const ring of d.split('M').filter(Boolean)) {
    const closed = ring.endsWith('Z');
    const pts = ring
      .replace('Z', '')
      .split('L')
      .map((pt) => pt.split(',').map(Number));
    const kept = [];
    for (const [x, y] of pts) {
      const last = kept[kept.length - 1];
      if (!last || Math.hypot(x - last[0], y - last[1]) >= min) kept.push([x, y]);
    }
    if (kept.length < (closed ? 3 : 2)) continue;
    out.push('M' + kept.map(([x, y]) => `${+x.toFixed(1)},${+y.toFixed(1)}`).join('L') + (closed ? 'Z' : ''));
  }
  return out.join('');
}
const p = geoPath(projection);
const landPath = round(p(land));
const gratPath = round(p(geoGraticule().step([20, 20])()));

const out = path.resolve('src/components/brand/globePaths.ts');
await fs.mkdir(path.dirname(out), { recursive: true });
await fs.writeFile(
  out,
  `// Generated by scripts/build-logo.mjs — Natural Earth land, orthographic projection.\nexport const GLOBE_LAND = ${JSON.stringify(landPath)};\nexport const GLOBE_GRATICULE = ${JSON.stringify(gratPath)};\n`,
);
console.log(`land ${landPath.length} chars, graticule ${gratPath.length} chars → ${out}`);
